# Generated by Django 5.2.6 on 2025-09-26 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voeux.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='Voeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Accepté', 'Accepté'), ('Refusé', 'Refusé')], default='En attente', max_length=50)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voeux.formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'formation')},
            },
        ),
    ]
